### ISSUE TITLE
Not working anymore on kernel 6.1.x

### ISSUE THREAD

**Issue by nlpsuge** [haikarainen/light#144]
`light` is not working anymore on kernel 6.1.x. The lightness is maximum when using  kernel 6.1.x. `light -S 10` can't change the lightness.

OS: Fedora 37
Kernel: 6.1.x

It works on Kernel 6.0.18.

Any suggestion?

**Comment by haikarainen** [comment]
Did your sysfs controller break? Do some debugging and figure out what happened.

Check around in `/sys/class/backlight/`

Run light in verbose mode and tell me what it spits out,

etc.

**Comment by plilq** [comment]
Also broke for me since latest updates after working well for years untouched. I am unable to currently compare kernels to specifically verify it's related to the same issue as originally reported, but figured this was the best bet.

`
% light -v 3 -U 2.5                                                                                   ~
helpers.c:21: Error: could not open '/home/user/.config/light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
`
It does not exist indeed, since .config/light is empty.

`% echo 15 > /sys/class/backlight/acpi_video0/brightness`

works as before, so no fundemendals have broken.

Arch kernel 6.2.2, light v1.2

**Comment by haikarainen** [comment]
The error for the minimum read should really be a warning, someone really fucked that some years ago.

Sounds like a permission issue though. Figure it out with the maintainer for the fedora package, open a new issue if it's actually an issue with light and not the package.

Should be mentioned this project is basically orphaned at this point, I donth ave time to work on it and apparently nobody else.

**Comment by nlpsuge** [comment]
As far as I know, this is caused by code changing of kernel 6.1.x.

I don't have a solution for the moment.

See also: 
https://discussion.fedoraproject.org/t/brightness-issue-fedora37/78985
https://www.reddit.com/r/voidlinux/comments/10ip5oy/screen_brightness_keys_stop_working_after_61/
https://hansdegoede.livejournal.com/26427.html

**Comment by plilq** [comment]
Alright, thanks for the updates, both of you.

What is a bit weird if it really is a kernel issue is that the underlying systems still work, /sys/class/backlight is still available as before and controllable directly. Maybe the underlying problem is different for me, but it's hard to judge since not much clarifying info is provided here with reports. In any case, it seems a bit moot if the project is not really maintained anymore.

I fixed my laptop buttons for myself by replacing light with the acpilight package and my bindings from 

`bindsym --release XF86MonBrightnessDown exec "light -U 2.5"`

to

`bindsym --release XF86MonBrightnessDown exec "xbacklight -dec 5"`

to get similar functionality without needing root access.

Thanks for all these years of having a simple utility for this though! :)

**Comment by nlpsuge** [comment]
`light` works again after removing the `acpi_backlight=video` from `/etc/default/grub`. And make sure to recreate the `grub.cfg` via `grub2-mkconfig -o /boot/grub2/grub.cfg`.

And even the `BrightnessDown / up` shortcut works finally on Gnome 43.3.
